### ISSUE TITLE
Fatal errors when upgrading due to null on Cloudflare::$api property.

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/cloudflare#15]
When first upgrading, getting the following fatal error:

```
Fatal error: Uncaught Error: Call to a member function set_api_credentials() on null in /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-content/plugins/wp-rocket/inc/Addons/Cloudflare/Cloudflare.php:567 
Stack trace: #0 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-content/plugins/wp-rocket/inc/Addons/Cloudflare/Subscriber.php(263): WPMedia\Cloudflare\Cloudflare->get_cloudflare_ips() 
#1 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-includes/class-wp-hook.php(286): WPMedia\Cloudflare\Subscriber->set_real_ip('') 
#2 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
#3 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) 
#4 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-settings.php(525): do_action('init') 
#5 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-config.php(106): require_once('/home/boniasty/...') 
#6 /ho in /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-content/plugins/wp-rocket/inc/Addons/Cloudflare/Cloudflare.php on line 567
```
Why?

1. WordPress fires the '`init`' event.
2. The `Subscriber::set_real_ip()` method is called.
3. There's not check to determine if `'do_cloudflare'` is on or off. <- Problem!
4. It calls `Cloudflare->get_cloudflare_ips()`.
5. But wait a minute, if `'do_cloudflare'` is off, then the `Cloudflare::$api` property was never set.
6. So when `Cloudflare->get_cloudflare_ips()` runs, `$api` is `null` and throws the fatal error.

Root cause:
Don't let the Subscriber call `Cloudflare` methods that require the `APIClient`. How? Check if `'do_cloudflare'` is on first. If no, bail out.

**Comment by crystinutzaa** [comment]
I'm not sure if we need the bailout for `set_real_ip`.
This function is called on `init` and even if Cloudflare is not enabled in WP Rocket, this function will run only if Cloudflare tries to connect to it:
```
if ( ! isset( $_SERVER['HTTP_CF_CONNECTING_IP'], $_SERVER['REMOTE_ADDR'] ) ) {
	return;	
}
```
Also, if there are no credentials for Cloudflare or Cloudflare addon is not enabled in WP Rocket, the function `get_cloudflare_ips` returns a default list of ips, so right now I'm not 100% sure where we should bail it out.
The issue seems to be in here while setting the credentials:
https://github.com/wp-media/cloudflare/blob/b5bfa20dd6a372dd8b1eb27910941d8c6e9cefeb/Cloudflare.php#L567-L577
The line:
`$this->api->set_api_credentials( $cf_email, $cf_api_key, '' );`
should be moved in try / catch block to prevent this Exception. 

What do you think?

**Comment by crystinutzaa** [comment]
I was thinking more about this issue and the question should be: what should WP Rocket do when Cloudflare addon is disabled related to the IP? Should WP Rocket affect this or not when Cloudflare addon is disabled?

If WP Rocket should not do anything, then the PR #16 is ready to go.

**Comment by hellofromtonya** [comment]
@crystinutzaa Let me ask a few questions for us to determine the right course of action:

1. How are the default or real Cloudflare IPs used in Rocket _when_ the customer's website is not using Cloudflare, i.e. it's turned off?
2. How did it work _before_ the rewrite, i.e. before 3.5?
3. If Rocket is not using the CF IPs without the addon being turned on, @Tabrisrp and @crystinutzaa, why are we getting the CF IPs at `'init'`?

**Comment by crystinutzaa** [comment]
1. The Cloudflare IPS are used to set the correct $_SERVER['REMOTE_ADDR'] : Set Real IP from CloudFlare. I pretty sure these are not used anywhere else in WP Rocket.

2. Before 3.5 rewrite, it required the CF user & password (no zone_id) otherwise sent the default IPs. 
https://github.com/wp-media/wp-rocket/blob/improvement/multiple_log_files/inc/common/cloudflare.php

3. Before the rewrite in init there were 2 operations done:
- Set the header: `header( 'X-CF-Powered-By: WP Rocket ' . WP_ROCKET_VERSION );`
- Set the Remote Addr: `$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];`

**Comment by hellofromtonya** [comment]
Let's get a baseline of understanding. Then I'll make some assertions.

Whether Cloudflare is enabled or disabled is determined by the "Add-on status" toggle in the "ADD-ONS" tab in the Rocket dashboard:

-`do_cloudflare` is enabled _when_ the "Add-on status" is set to on.

<img width="939" alt="Screen Shot 2020-02-19 at 6 27 00 AM" src="https://user-images.githubusercontent.com/7284611/74834564-465f6e80-52e1-11ea-9d14-13ff72e0f8b8.png">

-`do_cloudflare` is disabled _when_ the "Add-on status" is not set to on. 

<img width="926" alt="Screen Shot 2020-02-19 at 6 27 15 AM" src="https://user-images.githubusercontent.com/7284611/74834474-157f3980-52e1-11ea-9f50-e64d51807d02.png">

Assertions:

1. _When disabled_, Rocket doesn't communicate with the Cloudflare.
2. _When disabled_, Rocket does not use the Cloudflare addon.
3. _When disabled_, Rocket need or use the Cloudflare real or default IPs.
4. Therefore, Rocket only uses the addon _when its enabled_.

@crystinutzaa @Tabrisrp Do you agree with these assertions?

**Comment by Tabrisrp** [comment]
Only point 3 is not entirely correct from the current state of the plugin. As Cristina said, the setting of the REMOTE_ADDR is not tied to the CF Add-On activation as of version 3.4.4. It will use default CF IPs if the Add-On is disabled/missing credentials.

We can decide to change this behaviour with 3.5, and only do it when the add-on is active. This can make more sense, everything off or everything on depending on the add-on state.

**Comment by hellofromtonya** [comment]
>Only point 3 is not entirely correct from the current state of the plugin. As Cristina said, the setting of the REMOTE_ADDR is not tied to the CF Add-On activation as of version 3.4.4. It will use default CF IPs if the Add-On is disabled/missing credentials.

@Tabrisrp Why does Rocket need `REMOTE_ADDR` set to one of the CF IPs if CF is disabled on the website? Will it use it for anything else other than CF?

**Comment by Tabrisrp** [comment]
The add-on could be disabled, but Cloudflare itself enabled for the website.

But it's not mandatory that we do that, as I said we can change the behaviour and only handle this when the add-on is active.

**Comment by hellofromtonya** [comment]
>The add-on could be disabled, but Cloudflare itself enabled for the website.

@Tabrisrp What happens in this use case? Does Rocket use CF? Will CF take precedence over Rocket and be enabled and working?

**Comment by Tabrisrp** [comment]
Cloudflare will be enabled on the website (not the add-on). The Add-On is there as a convenience tool to sync up Rocket & Cloudflare cache & settings.

**Comment by hellofromtonya** [comment]
>Cloudflare will be enabled on the website (not the add-on). The Add-On is there as a convenience tool to sync up Rocket & Cloudflare cache & settings.

Okay, when Cloudflare is enabled on the website through the website or some other means, it works. Period. It doesn't care if the Addon is enabled or not in Rocket. Is this correct?

If yes, what happens in Rocket when Cloudflare is working on the website (outside of Rocket) but the Addon is disabled within Rocket?

**Comment by Tabrisrp** [comment]
> Okay, when Cloudflare is enabled on the website through the hosting or some other means, it works. Period. It doesn't care if the Addon is enabled or not in Rocket. Is this correct?

Correct

> If yes, what happens in Rocket when Cloudflare is working on the website (outside of Rocket) but the Addon is disabled within Rocket?

Currently: modifying the `REMOTE_ADDR` to set it to the real website domain/IP, instead of the Cloudflare one. That's it.

**Comment by hellofromtonya** [comment]
>Currently: modifying the `REMOTE_ADDR` to set it to the real website domain/IP, instead of the Cloudflare one. That's it.

For Rocket, it sets the `REMOTE_ADDR` to `HTTP_CF_CONNECTING_IP` when the IP matches one of the Cloudflare IPs. 

Is this the behavior we want and need. Does Rocket need the website's real domain/IP address for other processing? I assume yes, but asking to make sure.

**Comment by Tabrisrp** [comment]
Rocket no, I believe it's more for analytics purpose, to make sure the visitors origins are correct (instead of them using the Cloudflare server location)

**Comment by hellofromtonya** [comment]
After discussing this privately with Remy, here's what we decided:

1. If the Rocket addon is off, then this package's code should not be loaded into memory or run.
2. Within this package, there's no need to check the state of `do_cloudflare`. Why? This package won't be loaded into memory. <- this makes this package more reusable, i.e. less coupling to Rocket.
3. The `/ips` endpoint doesn't need credentials, i.e. `X-Auth-Email` or `X-Auth-Key` in the headers. Let's remove that requirement and checks from the `APIClient`.  <- this makes this package more reusable.
